package com.ravi.patient.app.constant;

public interface DBConstants {
	
	String QUERY_SEARCHPATIENTBYID = "SELECT * from PATIENT WHERE ID=?";
	String QUERY_SEARCHPATIENTMEDICALHISTBYPATIENTID = "SELECT * from PATIENTMEDICALHISTORY WHERE PATIENTID=?";
	String QUERY_GETMAXPATIENTID = "SELECT MAX(ID) from PATIENT";
	String QUERY_GETMAXPATIENTMEDICALHISTORYID = "SELECT MAX(ID) from PATIENTMEDICALHISTORY";
	String QUERY_DELETEPATIENTBYID = "DELETE from PATIENT WHERE ID=?";
	String QUERY_DELETEPATIENTMEDHISTORYBYID = "DELETE from PATIENTMEDICALHISTORY WHERE PATIENTID=?";
	String QUERY_INSERTPATIENT = "INSERT INTO PATIENT(ID, FIRSTNAME,LASTNAME, ADDRESS,EMAIL,PHONENUMBER,CITY,STATE,GENDER,DOB,SSN)"
			+ "VALUES (?, ?, ?,?,?,?,?,?,?,?,?)";
	String QUERY_INSERTPATIENTMEDIHISTORY = "INSERT INTO PATIENTMEDICALHISTORY(ID,PATIENTID,HEIGHT, WEIGHT,BLOODPRESSURE,PULSERATE,AFFECTEDORGAN)"
			+ "VALUES (?, ?, ?,?,?,?,?)";
	String QUERY_UPDATEPATIENT = "UPDATE PATIENT SET FIRSTNAME=?,LASTNAME=?,ADDRESS=?,EMAIL=?,PHONENUMBER=?,CITY=?,STATE=?,GENDER=?,DOB=?,SSN=? "
			+ " WHERE ID=?";
	String QUERY_UPDATEPATIENTMEDHISTORY = "UPDATE PATIENTMEDICALHISTORY SET HEIGHT=?,WEIGHT=?,BLOODPRESSURE=?,PULSERATE=?,AFFECTEDORGAN=?"
			+ " WHERE PATIENTID=?";
	String QUERY_GETALLPHYSICIANS = "SELECT * from PHYSICIAN";
	String QUERY_CHECKAPPOINTMENTSLOTAVAILABLE = "SELECT * from APPOINTMENTSLOTS WHERE PHYSICIANNAME=? AND APPOINTMENTDATE=? AND APPOINTMENTSLOT=?";
	String QUERY_BOOKAPPOINTMENTFORPATIENT = "INSERT INTO APPOINTMENTSLOTS(ID,APPOINTMENTID,PATIENTID,PHYSICIANID,PHYSICIANNAME,APPOINTMENTDATE,APPOINTMENTSLOT)"
			+ " VALUES(?,?,?,?,?,?,?);";
	String QUERY_GETMAXIDFORAPPOINTMENTS = "SELECT MAX(ID) from APPOINTMENTSLOTS";
	String QUERY_CHECKAPPOINTMENTEXISTSFORPATIENTID = "SELECT ID from APPOINTMENTSLOTS WHERE PATIENTID=?";
	String QUERY_CANCELAPPOINTMENTFORPATIENTID = "DELETE FROM APPOINTMENTSLOTS WHERE PATIENTID=? ";
	String QUERY_RESCHEDULEAPPOINTMENTFORPATIENTID = "UPDATE APPOINTMENTSLOTS SET PHYSICIANID=?,DRNAME=?,APPOINTMENTDATE=?,APPOINTMENTSLOT=? "
			+ " WHERE PATIENTID=?;";
	String QUERY_GETAPPOINTMENTBYPATIENTID = "SELECT APPOINTMENTID from APPOINTMENTSLOTS WHERE PATIENTID=?";
	String QUERY_GETALLAPPOINTMENTSFORPATIENTID = "SELECT * from APPOINTMENTSLOTS WHERE PATIENTID=?";
}
